### ISSUE TITLE
Update README title

### ISSUE THREAD

**Issue by RohanAlexander** [leoyliu/Estimating-State-Level-Doctoral-Degree-Attainment#2]
Can you please remove the - in the README title?
"Estimating-State-Level-Doctoral-Degree-Attainment" in https://github.com/leoyliu/Estimating-State-Level-Doctoral-Degree-Attainment/blob/main/README.md should be "Estimating State Level Doctoral Degree Attainment"

**Comment by leoyliu** [comment]
Sure! I've updated the README title to "Estimating State Level Doctoral Degree Attainment" as requested.
